### DISCUSSION TITLE
User mode (ALSA mode only)

### DISCUSSION THREAD

**Discussion by GioF71** [GioF71/squeezelite-docker#253] [Announcements]
Example docker-compose file for user mode with alsa:

```
---
version: '3.3'

services:
  squeezelite-d10-vanilla:
    image: giof71/squeezelite
    container_name: squeezelite-d10
    user: "1000:29"
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PRESET=topping-d10-sw
      - SQUEEZELITE_MODEL_NAME=Topping D10 (sq)
      - SQUEEZELITE_NAME=Topping D10 (sq)
      - CONFIG_FILE_PREFIX=d10-vanilla
    volumes:
      - /var/cache/docker-data/squeezelite:/config
```  

Make sure that the path you attach to volume /config is writable by the uid/gid you specify in `user`.
A host path should work, but a docker volume won't (at least doesn't work for me) because the container will not be able to write there.

Enjoy!
