### ISSUE TITLE
Hissing noise when playing DSF files

### ISSUE THREAD

**Issue by RobinpCP** [GioF71/squeezelite-docker#52]
I'm using Libreelec on RPi 3B+.  My Docker-compose file is

version: "3.3"

services:
  squeezelite-tailscale:
    image: giof71/squeezelite:latest
    container_name: squeezelite-tailscale
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_NAME=Squeezelite-Docker
      - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=sndrpihifiberry,DEV=0
      - SQUEEZELITE_TIMEOUT=3
      - STARTUP_DELAY_SEC=3
    restart: unless-stopped

These settings can play Flac and wav files.  My Hifiberry DAC2 Pro can support up to 192Khz/24bit which can play DSD64 files with no issues, because I've tried the following.

I downloaded Squeezelite from SourceForge and ran it from SSH terminal using command line 
/storage/squeezelite -o default:CARD=sndrpihifiberry -n 'Kodi-Squeezelite' -C 3

BTW, the latest version is now 1.9.9.1043.

**Comment by GioF71** [comment]
Hello,
as far as I know, the HiFiBrerry DAC2 Pro does not natively play DSD. When it does appear to do so, it is because the player converts those files to regular PCM.

About the versions: 1403 is only for the ffmpeg version, which I am not using.  It seems I am still using the most recent version of SqueezeLite on my images, which in the case of armhf is currently 1401.
But this might be the answer: when you run squeezelite from the command line using that binary, your version of squeezelite is probably doing the conversion by itself. This will generate high(er) cpu usage on the player, something to be considered if your player is a raspberry pi 3 or 2.

You might try with the no-dsd preset which will tell the LMS server that the player cannot or does not want to play dsd natively. This should force the LMS server to do the conversion if needed.
Here is the updated docker-compose file:

```
---
version: "3.3"

services:
  squeezelite-tailscale:
  image: giof71/squeezelite:latest
  container_name: squeezelite-tailscale
  network_mode: host
  devices:
    - /dev/snd:/dev/snd
  environment:
    - PRESET=no-dsd
    - SQUEEZELITE_NAME=Squeezelite-Docker
    - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=sndrpihifiberry,DEV=0
    - SQUEEZELITE_TIMEOUT=3
    - STARTUP_DELAY_SEC=3
  restart: unless-stopped
```

A side note: the suffix "-tailscale" for the service and container names is probably meaningless in your scenario. I am using those names for a RPI that I sometimes brought away from home and connected via a hotspot to my LMS server using the tailscale private network.
