### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by joinstuff** [GioF71/squeezelite-docker#6]
Hi  ,  I am using your  docker-compose file   with  a Topping E30  DAC ,  LMS and Squeezelite in containers.  However even if LMS sees the Sqeezelite player as functional , sound is not played in the speakers.   Any ideas why this is happening ?

**Comment by GioF71** [comment]
Hello, I have been away on holiday for a few days, I will come back to you as soon as I can.

**Comment by GioF71** [comment]
Can you provide your docker run command or docker compose file, along with the output of the command:

`aplay -L`

Thank you

**Comment by vespadj** [comment]
Same here.
`Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l`


on [https://hub.docker.com/r/giof71/squeezelite](https://hub.docker.com/r/giof71/squeezelite)
`docker run -d --rm --network host --device /dev/snd --net host giof71/squeezelite:stable`
returns error: double `host`

So running by:
`docker run --privileged -it -i --entrypoint=/bin/bash -t giof71/squeezelite:stable`
works and sounds to hdmi.

I would like to use docker-compose and headphone jack.

By docker-compose, run and connect but any sound.
```yaml
  squeezelite:
    image: giof71/squeezelite:stable
    container_name: squeezelite
    devices: 
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_NAME=home-pi
      #- SQUEEZELITE_AUDIO_DEVICE=hw:CARD=Headphones,DEV=0
      #- SQUEEZELITE_AUDIO_DEVICE=default:CARD=Headphones
      - SQUEEZELITE_AUDIO_DEVICE=default:CARD=b1
      - SQUEEZELITE_SERVER_PORT=192.168.1.9:3483
      - SQUEEZELITE_RATES="44100,48000,88200,96000,176400,192000,352800,384000"
      - SQUEEZELITE_UPSAMPLING="v::4:28:95:105:45"
      - STARTUP_DELAY_SEC=1
    restart: unless-stopped
```

I login to
`docker run --privileged -it -i --entrypoint=/bin/bash -t giof71/squeezelite:stable`
(I use this but I'm not sure it is correct), then
`aplay -L`
returns:
`bash: aplay: command not found`

I also try:
`# /usr/bin/squeezelite -l`
```shell
Output devices:
  null                           - Discard all samples (playback) or generate zero samples (capture)
  default:CARD=b1                - bcm2835 HDMI 1, bcm2835 HDMI 1 - Default Audio Device
  sysdefault:CARD=b1             - bcm2835 HDMI 1, bcm2835 HDMI 1 - Default Audio Device
  dmix:CARD=b1,DEV=0             - bcm2835 HDMI 1, bcm2835 HDMI 1 - Direct sample mixing device
  dsnoop:CARD=b1,DEV=0           - bcm2835 HDMI 1, bcm2835 HDMI 1 - Direct sample snooping device
  hw:CARD=b1,DEV=0               - bcm2835 HDMI 1, bcm2835 HDMI 1 - Direct hardware device without any conversions
  plughw:CARD=b1,DEV=0           - bcm2835 HDMI 1, bcm2835 HDMI 1 - Hardware device with all software conversions
  default:CARD=Headphones        - bcm2835 Headphones, bcm2835 Headphones - Default Audio Device
  sysdefault:CARD=Headphones     - bcm2835 Headphones, bcm2835 Headphones - Default Audio Device
  dmix:CARD=Headphones,DEV=0     - bcm2835 Headphones, bcm2835 Headphones - Direct sample mixing device
  dsnoop:CARD=Headphones,DEV=0   - bcm2835 Headphones, bcm2835 Headphones - Direct sample snooping device
  hw:CARD=Headphones,DEV=0       - bcm2835 Headphones, bcm2835 Headphones - Direct hardware device without any conversions
  plughw:CARD=Headphones,DEV=0   - bcm2835 Headphones, bcm2835 Headphones - Hardware device with all software conversions

```


Finally, `aplay -L` run in the system terminal: 
```shell

default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
sysdefault:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
dmix:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample mixing device
dsnoop:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample snooping device
hw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct hardware device without any conversions
plughw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Hardware device with all software conversions
usbstream:CARD=b1
    bcm2835 HDMI 1
    USB Stream Output
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output

```
As you can see above I try three `SQUEEZELITE_AUDIO_DEVICE`, but any sounds.
Sorry for long post.
I hope can this help to resolve.
Thanks
